# Generated by Django 5.0.6 on 2024-05-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.CharField(choices=[('factory', '0'), ('retail_network', '1'), ('IP', '2')], default='0', verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_suppliers', to='suppliers.supplier', verbose_name='supplier'),
        ),
    ]
