# Generated by Django 5.0.6 on 2024-05-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_level_alter_supplier_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail Network'), (2, 'Ip')], default=0, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_suppliers', to='suppliers.supplier', verbose_name='supplier'),
        ),
    ]
