# Generated by Django 5.0.6 on 2024-05-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_level_alter_supplier_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_suppliers', to='suppliers.supplier', verbose_name='supplier'),
        ),
    ]
