# Generated by Django 5.0.6 on 2024-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.IntegerField(choices=[(0, 'factory'), (1, 'retail network'), (2, 'ip')], default=0, verbose_name='level'),
        ),
    ]
