# Generated by Django 5.0.6 on 2024-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_alter_supplier_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.CharField(choices=[('FA', 'factory'), ('RT', 'retail network'), ('IE', 'ip')], default='FA', verbose_name='level'),
        ),
    ]
