# Generated by Django 4.2.7 on 2024-05-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.IntegerField(choices=[(0, 'zero level'), (1, 'first level'), (2, 'second level')], default=0, verbose_name='level'),
        ),
    ]
