# Generated by Django 4.2.7 on 2024-05-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_supplier_type_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'zero level'), (1, 'first level'), (2, 'second level')], null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('FA', 'factory'), ('RN', 'retail network'), ('IE', 'ip')], default='FA', verbose_name='type'),
            preserve_default=False,
        ),
    ]
