# Generated by Django 4.2.7 on 2024-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='level'),
        ),
    ]
