# Generated by Django 4.2.7 on 2024-05-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0019_alter_supplier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'zero level'), (1, 'first level'), (2, 'second level')], null=True, verbose_name='level'),
        ),
    ]
